-- MySQL Script generated by MySQL Workbench
-- Fri May 23 22:44:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_motus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_motus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_motus` ;
USE `projet_motus` ;

-- -----------------------------------------------------
-- Table `projet_motus`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_motus`.`Player` (
  `playerID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `points` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`playerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `projet_motus`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_motus`.`Game` (
  `gameID` INT NOT NULL AUTO_INCREMENT,
  `wordToGuess` VARCHAR(45) NULL,
  `playerID` INT NOT NULL,
  PRIMARY KEY (`gameID`),
  INDEX `fk_Game_playerID_idx` (`playerID` ASC) VISIBLE,
  CONSTRAINT `fk_Game_playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `projet_motus`.`Player` (`playerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
